global:
  scrape_interval: 5s
  evaluation_interval: 4s

scrape_configs:
  # Scrape your Flask API (running on the host at port 8080)
  - job_name: "recommender"
    static_configs:
      - targets: ["movie-reco-api:8080"]
        labels:
          service: "recommender-api"
          
  - job_name: "kafka-exporter"
    static_configs:
      - targets: ["kafka-exporter:9308"]

